### ISSUE TITLE
Line Coverage builds are failing

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#120] opened 2021-03-10 14:42 UTC
Line Cov builds has been failing for the last 28 days .
https://build.gluster.org/job/line-coverage/

Please fix the issue.

**Comment by deepshikhaaa** [comment] 2021-03-11 10:02
The job is failing because the regression test seems to be failing. Though it has recorded the lcov result.
From: https://build.gluster.org/job/line-coverage/1362/consoleFull
Overall coverage rate:
01:14:45   lines......: 70.6% (195298 of 276509 lines)
01:14:45   functions..: 85.2% (11574 of 13578 functions)
01:14:45 The HTML report is generated as index.html file

**Comment by mscherer** [comment] 2021-03-11 11:08
```
19:42:52 9 test(s) failed 
19:42:52 ./tests/basic/distribute/force-migration.t
19:42:52 ./tests/basic/metadisp/metadisp.t
19:42:52 ./tests/bugs/distribute/bug-1247563.t
19:42:52 ./tests/bugs/distribute/bug-1543279.t
19:42:52 ./tests/bugs/fuse/bug-1309462.t
19:42:52 ./tests/bugs/glusterd/bug-1238706-daemons-stop-on-peer-cleanup.t
19:42:52 ./tests/bugs/replicate/bug-1473026.t
19:42:52 ./tests/bugs/replicate/bug-802417.t
19:42:52 ./tests/features/ipc.t
19:42:52 
19:42:52 1 test(s) generated core 
19:42:52 ./tests/features/ipc.t
```

This is weird.

**Comment by msaju** [comment] 2021-03-12 05:13
It's a bit weird since the same set of tests runs fine with centos-8 regression.
https://build.gluster.org/job/centos8-regression/246/consoleText

The lcov builds is not running for a couple of days now, is it stopped explicitly?

**Comment by msaju** [comment] 2021-03-15 04:24
The build has passed today after a long time - https://build.gluster.org/job/line-coverage/1363/
Are there any specific changes done?.

**Comment by deepshikhaaa** [comment] 2021-03-15 07:00
It was failing earlier mainly because regression and smoke tests were failing, though lcov report was generated. I send a fix for the same. It will not return the exit code as per the test suite failure.

Also, we are looking at the tests that failed in the regression test suite.

**Comment by mscherer** [comment] 2021-12-22 10:43
So since lcov is not green, I am closing that bug.

**Closed as completed by mscherer** 2021-12-22 10:43 UTC
