### ISSUE TITLE
[bug:1713260] Using  abrt-action-analyze-c on core dumps  on CI

### ISSUE THREAD

**Issue by gluster-ant** [gluster/project-infrastructure#44] opened 2020-03-13 11:29 UTC
URL: https://bugzilla.redhat.com/1713260
Creator: sankarshan at redhat
Time: 20190523T09:38:02

Originally pointed out by Yaniv to "run abrt-action-analyze-c on core dumps we have in CI, to see if they are unique or we've seen them before. I have some failure that I'm quite sure has nothing to do with my patch (looks like we try to destroy an xlator that was not initialized?) and it'd be great to use DUPHASH."

Please review this and scope in terms of the work required to enable such.

**Comment by mscherer** [comment] 2021-12-22 10:45
Duplicate of #10

**Closed as completed by mscherer** 2021-12-22 10:45 UTC
Labels: Migrated, Type:Bug
