### ISSUE TITLE
gh-devrpm-fedora builds are failing

### ISSUE THREAD

**Issue by msaju** [gluster/project-infrastructure#121] opened 2021-03-11 03:58 UTC
rpm fedora builds upstream is failing due to the below reason.

20:05:05 Error Summary
20:05:05 -------------
20:05:05 Disk Requirements:
20:05:05    At least 343MB more space needed on the / filesystem.

**Comment by deepshikhaaa** [comment] 2021-03-11 05:02
It is an issue with builder49 which ran out of space. I did disconnect the builder from jenkins instance.

**Comment by mscherer** [comment] 2021-03-11 07:03
Mhh, builder49 just got reinstalled for planet, I guess something went wrong.

**Comment by mscherer** [comment] 2021-03-11 07:06
Log, for the record: https://build.gluster.org/job/gh_devrpm-fedora/1178/

**Comment by mscherer** [comment] 2021-03-11 07:09
I removed it from the fedora32 group, so the rpm jobs should no longer go there, only planet and bugs summary (bugs summary being soon deprecated).

**Comment by deepshikhaaa** [comment] 2021-03-11 09:23
builder49 is still disconnected. should I connect back? @mscherer

**Comment by itisravi** [comment] 2021-03-12 04:08
https://build.gluster.org/job/gh_devrpm-fedora/1186/console failed on  builder-f32-2.int.aws.gluster.org, so I think the issue is still there.

**Comment by deepshikhaaa** [comment] 2021-03-12 05:09
It is a different issue. Yesterday, I fixed it by manually deleting the leftovers of previous runs. But we need to handle this issue from the script. I am looking into it.

**Comment by msaju** [comment] 2021-03-22 04:10
Looks like some missing scripts...
https://ci.centos.org/view/Gluster/job/gluster_build-rpms/15094/console

**Comment by deepshikhaaa** [comment] 2021-03-22 04:44
Sent the fix for the same. Closing it now.

**Closed as completed by deepshikhaaa** 2021-03-22 04:44 UTC
