### ISSUE TITLE
Install dependencies for tcmalloc on all machines

### ISSUE THREAD

**Issue by amarts** [gluster/project-infrastructure#140] opened 2021-09-08 14:44 UTC
So that gluster/glusterfs#2773 and likes can proceed.

**Comment by mohit84** [comment] 2021-09-10 01:59
To use tcmalloc we have to install gperftools-libs also.

**Comment by mohit84** [comment] 2021-09-10 12:14
@mscherer Please update when you are able to install dependencies thereafter i will upload a patch.

**Comment by mscherer** [comment] 2021-09-13 10:47
Oups, sorry, forgot to update this bug. yep, this was done, I just didn't hit enter :(

**Comment by mohit84** [comment] 2021-09-13 16:36
It seems tcmalloc is not installed on all the machines, smoke build is failing on this https://github.com/gluster/glusterfs/pull/2773

**Comment by deepshikhaaa** [comment] 2021-09-14 05:53
@mohit84 We have installed both gperftools-devel and gperftools-libs package on all the machines. 

I can confirm on builder1 where devrpm-el7 is running https://build.gluster.org/job/gh_devrpm-el7/2070/
`[root@builder1 ~]# rpm -q gperftools-devel
gperftools-devel-2.6.1-1.el7.x86_64

[root@builder1 ~]# rpm -q gperftools-libs
gperftools-libs-2.6.1-1.el7.x86_64`

Is there anything we are missing here?

**Comment by mscherer** [comment] 2021-09-14 09:21
Seems we also need google-perftools on Freebsd, as pointed by @rakshithakamath94 , and our FreeBSD builder was in a weird state. I fixed by changing the repo location (eg, http to https), and installed the package. going to add in ansible as well.

**Comment by rakshithakamath94** [comment] 2021-09-16 04:33
The job [gh_freebsd-smoke](https://build.gluster.org/job/gh_freebsd-smoke/) is failing due to some dependency resolution issue. For the timing the job will be marked as successful though there's a failure. This is to unblock the PRs and we are working on this issue and we will fix the issue ASAP.

**Comment by mscherer** [comment] 2021-09-16 08:45
Indeed, it seems that after running pkg upgrade, some binary packages are complaining about missing symbol. @deepshikhaaa noted that the updated binary packages were likely made for 12.2, and we are still on 12.1. So upgrade time.

**Comment by mscherer** [comment] 2021-09-16 09:09
So the upgrade is done, let's see how it goes.

**Comment by rakshithakamath94** [comment] 2021-09-16 17:01
After the successful upgrade by @mscherer the job's are passing as the old times. So, bringing the normal configuration back for [gh_freebsd-smoke](https://build.gluster.org/job/gh_freebsd-smoke/).

**Comment by mscherer** [comment] 2021-09-17 08:47
For the record, the upgrade didn't go well. We had to reinstall the system, and I still do not know what broke, or when, it might have been a package upgrade gone wrong.

**Comment by mscherer** [comment] 2021-10-20 08:06
Closing, since https://github.com/gluster/glusterfs/pull/2787 was merged.

**Closed as completed by mscherer** 2021-10-20 08:06 UTC
