### ISSUE TITLE
test case ./tests/basic/glusterd/arbiter-volume-probe.t is continuously failing

### ISSUE THREAD

**Issue by mohit84** [gluster/project-infrastructure#94] opened 2020-10-14 04:57 UTC
The test case( ./tests/basic/glusterd/arbiter-volume-probe.t ) on the build https://build.gluster.org/job/gh_centos7-regression/84/consoleFull is continuously failing even the patch is not related with this codepath.I have observed the test case is failing only while running a centos-regression, in case of running a full regression the test case is not failing.
After checked the logs i have found it is failing because glusterd is not able to resolve ip_address, dns getaddr call is failing.
I am seeing below dns call errors in the peer end glusterd logs

 [2020-10-12 05:20:19.499470 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:22.512472 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:25.514032 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:28.515492 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:31.516965 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:34.518298 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:37.519522 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:40.521396 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:43.522675 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:46.524191 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:49.525539 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:52.526780 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:55.528278 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:20:58.529711 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:01.532417 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:04.533864 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:07.535464 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:10.536967 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:13.538412 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:16.539953 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:20.806471 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal
[2020-10-12 05:21:23.808372 +0000] E [name.c:265:af_inet_client_get_remote_sockaddr] 0-management: DNS resolution failed on host ip-127-1-1-1.us-east-2.compute.internal

**Comment by deepshikhaaa** [comment] 2020-10-14 05:10
It seems to be failing on c7-3 builder only. I am disconnecting it for now.

**Comment by mscherer** [comment] 2020-10-14 10:12
SO, we diagnosed that to be caused by wring DNS on that builder. We had automation to fix that (changing the setting on dhcp, since it keep rewriting resolv.conf), but this wasn't enough. I have added a more forceful change for that, and it should be deployed now.

**Comment by mscherer** [comment] 2021-10-20 08:14
Closing, seems to no longer be a issue.

**Closed as completed by mscherer** 2021-10-20 08:14 UTC
