### ISSUE TITLE
Gluster build checker is failing with '/tmp/jenkins3628232026354163899.sh: line 3: /opt/rh/python27/enable: No such file or directory'

### ISSUE THREAD

**Issue by kshithijiyer** [gluster/project-infrastructure#77] opened 2020-09-02 04:25 UTC
Failed Job: https://build.gluster.org/job/glusto-tests-lint/6130/console

```
09:43:25 Triggered by Gerrit: https://review.gluster.org/24937
09:43:25 Running as SYSTEM
09:43:25 Building remotely on builder-c7-2.int.aws.gluster.org (smoke7 centos7) in workspace /home/jenkins/root/workspace/glusto-tests-lint
09:43:25 No credentials specified
09:43:25 Wiping out workspace first.
09:43:25 Cloning the remote Git repository
09:43:25 Cloning repository git://review.gluster.org/glusto-tests.git
09:43:25  > git init /home/jenkins/root/workspace/glusto-tests-lint # timeout=10
09:43:25 Fetching upstream changes from git://review.gluster.org/glusto-tests.git
09:43:25  > git --version # timeout=10
09:43:25  > git fetch --tags --progress git://review.gluster.org/glusto-tests.git +refs/heads/*:refs/remotes/origin/* # timeout=10
09:43:26  > git config remote.origin.url git://review.gluster.org/glusto-tests.git # timeout=10
09:43:26  > git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* # timeout=10
09:43:26  > git config remote.origin.url git://review.gluster.org/glusto-tests.git # timeout=10
09:43:26 Fetching upstream changes from git://review.gluster.org/glusto-tests.git
09:43:26  > git fetch --tags --progress git://review.gluster.org/glusto-tests.git refs/changes/37/24937/3 # timeout=10
09:43:27  > git rev-parse 58a21bc0606f5267e3ff981bf8e729da443c551b^{commit} # timeout=10
09:43:27 JENKINS-19022: warning: possible memory leak due to Git plugin usage; see: https://wiki.jenkins.io/display/JENKINS/Remove+Git+Plugin+BuildsByBranch+BuildData
09:43:27 Checking out Revision 58a21bc0606f5267e3ff981bf8e729da443c551b (refs/changes/37/24937/3)
09:43:27  > git config core.sparsecheckout # timeout=10
09:43:27  > git checkout -f 58a21bc0606f5267e3ff981bf8e729da443c551b # timeout=10
09:43:27 Commit message: "[Test] Add basic tests for different device files"
09:43:27  > git rev-parse FETCH_HEAD^{commit} # timeout=10
09:43:27  > git rev-list --no-walk 56700c693c061ff4f942630d793628059099b0e5 # timeout=10
09:43:27 [glusto-tests-lint] $ /bin/sh /tmp/jenkins3628232026354163899.sh
09:43:27 /tmp/jenkins3628232026354163899.sh: line 3: /opt/rh/python27/enable: No such file or directory
09:43:27 Build step 'Execute shell' marked build as failure
09:43:27 Finished: FAILURE
```

**Comment by mscherer** [comment] 2020-09-02 08:21
That's curious, I do not understand why we need to use the SCL provided python 2.7 (since that's the path where a software collections would be installed) , since it seems to be python 2.7, which is the system version on Centos 7.  I guess it might date back from Centos 6 days or something.

I am out for helping pack a flat today, so I will take a look later in the week, but I think the fix is to just remove that line, as it should work fine on Centos 7. Why wasn't it seen sooner is a mystery to investiate later.

**Comment by kshithijiyer** [comment] 2020-09-02 10:00
The series of failures are running on builder machine *builder-c7-2.int.aws.gluster.org * and failure message is same 
https://build.gluster.org/job/glusto-tests-lint/6129/console 
https://build.gluster.org/job/glusto-tests-lint/6130/console 
https://build.gluster.org/job/glusto-tests-lint/6131/console 
https://build.gluster.org/job/glusto-tests-lint/6132/console
```
09:54:25 Triggered by Gerrit: https://review.gluster.org/24937
09:54:25 Running as SYSTEM
09:54:25 Building remotely on builder-c7-2.int.aws.gluster.org (smoke7 centos7) in workspace /home/jenkins/root/workspace/glusto-tests-lint
09:54:25 No credentials specified
....
09:54:27 [glusto-tests-lint] $ /bin/sh /tmp/jenkins2964759750676418039.sh
09:54:27 /tmp/jenkins2964759750676418039.sh: line 3: /opt/rh/python27/enable: No such file or directory
09:54:27 Build step 'Execute shell' marked build as failure
09:54:27 Finished: FAILURE
```
One more failure seen on the same builder machine builder-c7-2.int.aws.gluster.org but due to java error as below:
```
00:51:30 Triggered by Gerrit: https://review.gluster.org/24935
00:51:30 Running as SYSTEM
00:51:30 Building remotely on builder-c7-2.int.aws.gluster.org (smoke7 centos7) in workspace /home/jenkins/root/workspace/glusto-tests-lint
00:51:30 No credentials specified
00:51:30 Wiping out workspace first.
04:28:19 FATAL: java.io.IOException: Unexpected termination of the channel
04:28:19 java.io.EOFException
```
In the last successful job, the builder machine is builder24.int.rht.gluster.org

Looks more like some issue with the builder not sure what.

**Comment by mscherer** [comment] 2020-10-13 10:14
The issue is that builder in the datacenter have a python27 rpm and not the one in AWS. While we could move that to AWS, I need to understand why 1st, because python 2.7 is the system version on Centos 7, ergo, why are we using SCL on Centos 7 ? (if not for historic reason with Centos 6 back in the day ) 

I did a test without it, and it work (at least on builder24). I will test on more than this builder to be sure.

**Comment by mscherer** [comment] 2020-10-13 10:16
So indeed, it work now on all builders: https://build.gluster.org/job/glusto-tests-lint/6415/console

**Comment by mscherer** [comment] 2021-12-22 10:22
Closing per last comment

**Closed as completed by mscherer** 2021-12-22 10:22 UTC
